"""Base Trading Strategy - Domain Layer.

Abstract base class for all trading strategies.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass
from decimal import Decimal
from enum import Enum
from typing import Any


class SignalType(str, Enum):
    """Trading signal types."""

    BUY = 'buy'
    SELL = 'sell'
    HOLD = 'hold'


@dataclass(frozen=True)
class MarketDataPoint:
    """Market data for strategy evaluation."""

    price: Decimal
    volume: int
    timestamp: str
    indicators: dict[str, Any] | None = None


@dataclass(frozen=True)
class StrategySignal:
    """Trading signal generated by strategy."""

    signal_type: SignalType
    instrument: str
    quantity: Decimal = Decimal('0')
    target_price: Decimal = Decimal('0')
    confidence: Decimal = Decimal('0')
    reason: str | None = None


class TradingStrategyBase(ABC):
    """
    Abstract base class for trading strategies.

    Pure domain logic - no infrastructure dependencies.
    """

    def __init__(self, parameters: dict) -> None:
        """
        Initialize strategy with parameters.

        Args:
            parameters: Strategy-specific configuration
        """
        self.parameters = parameters
        self._validate_parameters()

    @abstractmethod
    def _validate_parameters(self) -> None:
        """
        Validate strategy parameters.

        Raises:
            ValueError: If parameters are invalid
        """

    @abstractmethod
    def generate_signal(
        self,
        instrument: str,
        current_data: MarketDataPoint,
        historical_data: list[MarketDataPoint],
    ) -> StrategySignal:
        """
        Generate trading signal based on market data.

        Args:
            instrument: Trading instrument
            current_data: Current market data point
            historical_data: Historical data for analysis

        Returns:
            StrategySignal with buy/sell/hold decision
        """

    @abstractmethod
    def calculate_position_size(
        self,
        signal: StrategySignal,
        available_capital: Decimal,
        current_price: Decimal,
    ) -> Decimal:
        """
        Calculate position size for signal.

        Args:
            signal: Trading signal
            available_capital: Available capital for trading
            current_price: Current market price

        Returns:
            Position size (quantity)
        """
